-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXqTAPfHqghhMZ3EH
TBFM8OnCZe0FtBpYnaEWBDIc8GOgCgYIKoZIzj0DAQehRANCAAR18b3Ay77mphVD
x0diugfZ9VP/NZJ8q2xazMnNPTTMRolphNyRP60CeIaTIoww0AdvPfvncwzUq/uw
PrMc0Shh
-----END PRIVATE KEY-----