# Uncomment this line to define a global platform for your project
#ENV['SWIFT_VERSION'] = '5'
platform :ios, '12.0'
workspace 'Ambassador Education.xcworkspace'
#target 'T360' do

target 'PEPS V2' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'DGActivityIndicatorView'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'Toast-Swift', '~> 2.0.0'
pod 'RichEditorView','~> 4.0.0'
pod 'MBCalendarKit', '~> 5.0.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'MXSegmentedPager'
pod 'DropDown'
pod 'DatePickerDialog'
pod 'CCBottomRefreshControl'
pod 'FSCalendar'
pod 'BIZPopupView'
pod 'SwiftSoup'
#pod 'Firebase/Core','8.1.0'
pod 'FirebaseAnalytics', '~> 7.0.0'
#pod 'FirebaseAnalytics'
pod 'FirebaseDatabase', '~> 7.0.0'
pod 'SCLAlertView'
pod 'GGLInstanceID'
pod 'FirebaseMessaging'
pod 'EzPopup'

#pod 'Google/AdMob'
# Pods for Ambassador Education
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#  end
#end
end
