# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Takyon360Buzz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'DGActivityIndicatorView'
    pod 'BIZPopupView'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'MXSegmentedPager'
    pod 'DropDown'


end
