# Define the minimum deployment target
platform :ios, '16.0'

target 'Takyon360Buzz' do
  use_frameworks!

  # Add dependencies
  pod 'DGActivityIndicatorView'
  pod 'BIZPopupView'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'MXSegmentedPager'
  pod 'DropDown'

  # Force all pods to use iOS 16.0 and Swift 5.9 for compatibility
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
          config.build_settings['SWIFT_VERSION'] = '5.9'
        end
      end
    end
  end
end
